[avatar]
filetype = "image"
# 10 MB
max_size = 10485760
transformations = [{ id = "resize", width = 512, height = 512 }]

[spaceicon]
filetype = "image"
max_size = 10485760
transformations = [{ id = "resize", width = 512, height = 512 }]
