[package]
name = "muonic-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
muonic-core = { version = "0.1.0", path = "../core" }
proc-macro-error = "1.0"
proc-macro2 = "1.0.76"
