[workspace]
resolver = "2"
members = [
    "apps/content-proxy",
    "apps/superego",
    "packages/muonic",
    "packages/muonic/macros",
    "packages/muonic/core",
    "packages/hyperschema-rs",
]
