services:
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mikoto
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mikoto
    restart: always
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always