services:
  crdb:
    image: cockroachdb/cockroach:v22.2.2
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "./data/cockroach-data/crdb:/cockroach/cockroach-data"
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - "./data/minio:/data"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
  livekit:
    image: livekit/livekit-server:latest
    command: '--keys "devkey: secret"'
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882"
