services:
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always