version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "3090:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
