[package]
name = "muonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-query = { version = "0.30.7" }
sea-query-binder = { version = "0.5.0", features = [
    "sqlx-postgres",
    "with-json",
    "with-uuid",
    "with-time",
] }

[dependencies.sqlx]
version = "0.7"
features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "uuid",
    "time",
    "json",
    "migrate",
]
