name: Build Desktop App

on:
  push:
    paths:
      - apps/desktop/**
    branches: ['main']

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - run: yarn install

      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        working-directory: ./apps/desktop
        run: yarn publish
