name: Build Desktop App

on:
  push:
    paths:
      - apps/desktop/**
    branches: ['main']

env:
  GITHUB_TOKEN: ${{ secrets.github_token }}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - run: yarn install

      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        working-directory: ./apps/desktop
        run: yarn publish
