name: Publish Mikoto.js to NPM
on:
  push:
    paths:
      - packages/mikotojs/**
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i -g turbo
      - run: turbo prune --scope=mikotojs
      - run: yarn install
        working-directory: ./out
      - run: yarn build
        working-directory: ./out/packages/mikotojs
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./out/packages/mikotojs/package.json
