name: Publish Lucid UI to NPM
on:
  push:
    paths:
      - packages/lucid/**
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --immutable
      - run: yarn build
        working-directory: ./packages/lucid
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/lucid/package.json
